# Generated by Django 3.0.4 on 2020-04-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details_bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=40)),
                ('bcat', models.CharField(max_length=40)),
                ('btype', models.CharField(max_length=40)),
                ('bsymt', models.TextField(max_length=100)),
            ],
        ),
    ]
