# Generated by Django 3.0.4 on 2020-04-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('function_tag', models.TextField()),
                ('geometry', models.FileField(upload_to='geometry/')),
                ('mesh', models.FileField(upload_to='mesh/')),
            ],
        ),
    ]
